name: Upload on new tags

on:
  push:
    tags:
      '*'

jobs:
  buildAndUpload:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.7"
        architecture: "x86"
    - name: Install dependencies
      run: pip install scons markdown
    - name: Build add-on
      run: scons
    - name: Build pot template
      run: scons pot
    - name: Calculate sha256
      run: sha256sum *.nvda-addon >> changelog.md
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          *.nvda-addon
          *.json
          *.pot
        body_path: changelog.md
        prerelease: ${{ endsWith(github.ref, '-dev') }}
